artifact_location: /Users/pabloparedes/Documents/prophet_GB_demand_forecasting_workflow/mlflow_dir/0
creation_time: 1728657244624
experiment_id: '0'
last_update_time: 1728657244624
lifecycle_stage: active
name: Default
