channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.2
- pip:
  - traitlets==5.14.2
  - tornado==6.4
  - six==1.16.0
  - platformdirs==4.2.0
  - ipykernel==6.29.3
  - executing==2.0.1
  - asttokens==2.4.1
  - pygments==2.17.2
  - decorator==5.1.1
  - wcwidth==0.2.13
  - parso==0.8.3
  - jedi==0.19.1
  - comm==0.2.2
  - psutil==5.9.8
  - debugpy==1.8.1
  - packaging==23.2
  - appnope==0.1.4
  - ipywidgets==8.1.3
  - smmap==5.0.1
  - gitdb==4.0.11
  - numpy==1.26.4
  - defusedxml==0.7.1
  - cffi==1.16.0
  - pyparsing==3.1.2
  - cycler==0.12.1
  - kiwisolver==1.4.5
  - matplotlib==3.8.3
  - pytz==2024.1
  - cloudpickle==3.0.0
  - pyarrow==17.0.0
  - pandas==2.2.1
  - scipy==1.12.0
  - patsy==0.5.6
  - statsmodels==0.14.1
  - seaborn==0.13.2
  - holidays==0.24
  - tqdm==4.66.2
  - plotly==5.23.0
  - prophet==1.1.5
  - future==1.0.0
  - networkx==3.3
  - py4j==0.10.9.7
  - pyspark==3.5.1
  - hyperopt==0.2.7
  - wrapt==1.16.0
  - deprecated==1.2.14
  - zipp==3.20.2
  - urllib3==2.2.1
  - idna==3.6
  - certifi==2024.2.2
  - requests==2.31.0
  - sqlparse==0.5.1
  - cachetools==5.5.0
  - click==8.1.7
  - pydantic==2.7.0
  - mlflow==2.16.2
  - stanio==0.3.0
  - xarray==2024.9.0
  - cmdstanpy==1.2.1
name: mlflow-env
