artifact_location: /Users/pabloparedes/Documents/prophet_GB_demand_forecasting_workflow/mlflow_dir/128317944280752817
creation_time: 1728657244628
experiment_id: '128317944280752817'
last_update_time: 1728657244628
lifecycle_stage: active
name: GB_Daily
